// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'link': string;
  'main': string;
  'root': string;
  'sidebar': string;
  'tag': string;
  'tagError': string;
  'tagFail': string;
  'tagPass': string;
  'tagRunning': string;
  'tagSkip': string;
  'tagWaiting': string;
  'testError': string;
  'testList': string;
  'testListItem': string;
  'testTitle': string;
  'testTitleText': string;
}
declare var cssExports: CssExports;
export = cssExports;
